version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: frb_postgres
    environment:
      POSTGRES_DB: FRB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pitesti
    ports:
      - "5432:5432"
    volumes:
      - frb_data:/var/lib/postgresql/data
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql

volumes:
  frb_data:
